AppBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: AppBundle\Player\Repository\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        club:
            targetEntity: Club
            inversedBy: players
            joinColumn:
                name: clubId
                referencedColumnName: id
    lifecycleCallbacks: {  }
